name: Generate Snake Animation  

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Generate Snake Contributions
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: "ajeshkm"
          outputs: |
            dist/github-contribution-grid-snake.svg
            
      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
